log:
  identifier: "mvd"
  root_path: "./log_3dmatch"

render:
  augment_rotations: True
  draw_color: False
  draw_depth: True
  trainable: True
  view_num: 8
  rotation_num: 0

model:
  cnn_out_channels: 128
  desc_dim: 32
  fusion_type: "soft_pool"
  type: "MVPoolNet"

view_pool:
  kernel: 3

train:
  general:
    ckpt_path: "./ours_3dmatch/net_{}_16.pth"
  dataset:
    name: "3dmatch"
    pcloud_root: "<Fused_Fragments_Root>"
    kpts_root: "<Keypoints_Root>"

eval:
  general:
    ckpt_path: "./ours_3dmatch/net_{}_16.pth"
  geomreg:
    test:
      name: "3dmatch"
      pcloud_root: "<3DMatch_Root>"
